### ISSUE TITLE
Enable support for pretty_name in automod rules

### ISSUE THREAD

**Issue by RedSpid3r** [ZeppelinBot/Zeppelin#384]
Currently, you cannot use `pretty_name` in automod rules, so your alerts always end up with the raw name. 

eg
```
  automod:
    config:
      rules:
        urlFilter_inviteFilter:
          pretty_name : "Discord Invite Filter"
          triggers:
          - match_invites:
              allow_group_dm_invites: true
              match_messages: true
              match_visible_names: false
          actions:
            log: true
            clean: true
```
