### ISSUE TITLE
author.icon_url does not work in embed formatted logs

### ISSUE THREAD

**Issue by RedSpid3r** [ZeppelinBot/Zeppelin#389]
When using embed format logs, the `icon_url` for Author does not work:

```yml
        VOICE_CHANNEL_JOIN:
          embed: 
            author:
              name: "{member.tag} [{member.id}]"
              icon_url: "{user.avatarURL}"
            description: '<@{member.id}> joined voice channel <#{channel.id}>'
            thumbnail:
              url: '{member.user.avatarURL}'
            color: 0x77dd77 #pastel green
            footer: 
              text: "{timestamp}"

```

![image](https://user-images.githubusercontent.com/12657277/219946771-eddad59b-da93-4112-9fa1-2bb7225d1434.png)
